# Generated by Django 4.2.21 on 2025-06-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('current_occupancy', models.CharField(choices=[('Empty', 'Empty'), ('Medium', 'Medium'), ('Full', 'Full')], default='Empty', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
